"""Add missing virtual pet tables

Revision ID: b8fd08218a3f
Revises: 2b134afa2347
Create Date: 2025-09-23 21:46:07.872605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8fd08218a3f'
down_revision = '2b134afa2347'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('virtual_pets',
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('species', sa.String(length=50), nullable=False),
    sa.Column('happiness', sa.Float(), nullable=False),
    sa.Column('energy', sa.Float(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('last_fed', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_played', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pet_id')
    )
    op.create_index(op.f('ix_virtual_pets_pet_id'), 'virtual_pets', ['pet_id'], unique=False)
    op.create_index(op.f('ix_virtual_pets_user_id'), 'virtual_pets', ['user_id'], unique=True)
    op.create_table('pet_accessories',
    sa.Column('accessory_id', sa.Integer(), nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('accessory_type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon_url', sa.String(length=255), nullable=True),
    sa.Column('level_required', sa.Integer(), nullable=False),
    sa.Column('stats_boost', sa.Text(), nullable=True),
    sa.Column('is_equipped', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['pet_id'], ['virtual_pets.pet_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('accessory_id')
    )
    op.create_index(op.f('ix_pet_accessories_accessory_id'), 'pet_accessories', ['accessory_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pet_accessories_accessory_id'), table_name='pet_accessories')
    op.drop_table('pet_accessories')
    op.drop_index(op.f('ix_virtual_pets_user_id'), table_name='virtual_pets')
    op.drop_index(op.f('ix_virtual_pets_pet_id'), table_name='virtual_pets')
    op.drop_table('virtual_pets')
    # ### end Alembic commands ###
